services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: peysich
      POSTGRES_PASSWORD: peysich
      POSTGRES_DB: peysich
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
